---
# tasks file for anaconda role

- name: Download anaconda python distribution
  get_url: 
    url: http://repo.continuum.io/archive/Anaconda2-2.4.0-Linux-x86_64.sh
    dest: /tmp/anaconda.sh 
    mode: 0755
    force: no

- name: Execute the anaconda setup script
  shell: /tmp/anaconda.sh -b -p {{ anaconda_home }} creates={{ anaconda_home }} executable=/bin/bash
  notify:
    - remove anaconda setup script

- name: Add anaconda to the PATH
  shell: "echo '{{ item }}' >> /etc/profile executable=/bin/bash"
  with_items:
  - "export PATH={{ anaconda_home }}/bin:$PATH"

- name: Update conda to latest version
  shell: "{{ anaconda_home }}/bin/conda update conda --yes -q executable=/bin/bash"

- name: Update Anaconda packages.
  command: "{{ anaconda_home }}/bin/conda update anaconda"

- name: Install pip
  shell: "{{ anaconda_home }}/bin/conda install pip --yes -q executable=/bin/bash"

- name: Install jupyter
  shell: "{{ anaconda_home }}/bin/conda install jupyter --yes -q executable=/bin/bash"

- name: Creates directory /home/vagrant/.jupyiter
  file: path=/home/vagrant/.jupyter state=directory mode=0700 owner=vagrant group=vagrant

- name: Configure jupyter notebook
  template: src=jupyter_notebook_config.py.j2
            dest=/home/vagrant/.jupyter/jupyter_notebook_config.py
            mode=0664
            owner=vagrant group=vagrant

- name: Copy jupyter script
  template: src=spark_notebook.py.j2
            dest=/home/vagrant/spark_notebook.py
            mode=0755
            owner=vagrant group=vagrant

- name: Copy jupyter notebook conf to upstart directory
  template: src=notebook.conf.j2
            dest=/etc/init/notebook.conf
            mode=0644

- name: Start jupyter notebook.
  command: start notebook

